apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-joplin
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22300
  selector:
    app: {{ .Release.Name }}-joplin
